POST http://localhost:3003/signup
Content-Type: application/json

{
	"name": "Batata Scott",
	"email": "batata@dundermifflin.com",
	"password": "thebatata",
	"role": "ADMIN"
}


###

POST http://localhost:3003/login
Content-Type: application/json

{
	"email": "batata@dundermifflin.com",
	"password": "thebatata"
}