POST https://labenu-cookenu-eduardo.herokuapp.com/signup
Content-Type: application/json

{
    "name": "Aldeir",
    "email": "Aldeir@email.com",
    "password": "159456",
    "role": "ADMIN"
}

###

# @name login
POST https://labenu-cookenu-eduardo.herokuapp.com/login 
Content-Type: application/json

{ 
    "email": "Aldeir@email.com",
    "password": "159456"
}


###
@token = {{login.response.body.token}}
POST https://labenu-cookenu-eduardo.herokuapp.com/recipe
Content-Type: application/json
Authorization: {{token}}

{
    "title": "Café",
    "description": "Jogar água quente no pó de café."
}

###

@token = {{login.response.body.token}}
GET https://labenu-cookenu-eduardo.herokuapp.com/user/profile
Content-Type: application/json
Authorization: {{token}}

###

@token = {{login.response.body.token}}
GET https://labenu-cookenu-eduardo.herokuapp.com/user/3bfb3208-b9cb-4c64-999d-c3799b787c83
Content-Type: application/json
Authorization: {{token}}

###
@token = {{login.response.body.token}}
GET https://labenu-cookenu-eduardo.herokuapp.com/recipe/292f7ecb-c500-4f69-9c33-200bcc7eaefb
Content-Type: application/json
Authorization: {{token}}

